blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/SouptikTaran/FlowDocs/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📧 Security Issues
    url: https://github.com/SouptikTaran/FlowDocs/security/advisories/new
    about: Report security vulnerabilities privately
