name: Auto Assign Issues

on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    
    steps:
    - name: Auto-assign issue
      uses: pozil/auto-assign-issue@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        assignees: SouptikTaran
        numOfAssignee: 1

---

name: Welcome New Contributors

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    
    steps:
    - name: Welcome new contributors
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          👋 Welcome to FlowDocs! Thank you for creating your first issue. 
          
          Our team will review it soon. In the meantime, please:
          - Check if similar issues exist
          - Provide as much detail as possible
          - Join our [discussions](https://github.com/SouptikTaran/FlowDocs/discussions) if you have questions
          
          We appreciate your contribution to making FlowDocs better! 🚀
        pr-message: |
          🎉 Thank you for your first contribution to FlowDocs! 
          
          Please ensure:
          - [ ] Your PR follows our [contributing guidelines](CONTRIBUTING.md)
          - [ ] You've tested your changes
          - [ ] Documentation is updated if needed
          
          Our team will review your PR soon. Welcome to the community! 🚀
